version: '3.1'

services:
  db:
    image: localmssql:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: "m8p@assworD"
    ports:
      - 1433:1433
#    volumes:
#      - "pgdataV2160MSSQL:/var/opt/mssql/data/"
  planet9:
    image: neptunesoftware/planet9:v2.6.4
    environment:
      DB_TYPE: mssql
      DB_MSSQL_HOST: db
      DB_MSSQL_USER: sa
      DB_MSSQL_PASSWORD: "m8p@assworD"
      DB_MSSQL_PORT: 1433
      DB_MSSQL_SCHEMA: planet9
      DB_MSSQL_DBNAME: planet9
    ports:
      - 8080:8080
volumes:
  pgdataV2160MSSQL:
